### ISSUE TITLE
Popup are not opening with Safari latest version 10.1(11603.1.30.0.34), It's opening as tab.

### ISSUE THREAD

**Issue by NitinWabale** [krakenjs/xcomponent#107]
I am using xcomponent 2.0.64

**Comment by jmc265** [comment]
I had an issue like this recently in Chrome (not with xcomponent). It turned out that I was doing window.open with location=1 and for some reason Chrome didn't like that. So it might be best to look at the status, toolbar and menubar options here:
https://github.com/krakenjs/xcomponent/blob/master/src/component/parent/drivers.js#L191

Just a hunch though.

**Comment by bluepnume** [comment]
Do you see the problem on this test page when you click the button? http://bluesuncorp.co.uk/icv4/popup.htm

**Comment by NitinWabale** [comment]
I can not see  problem on this test page when i click the button.
http://bluesuncorp.co.uk/icv4/popup.htm

**Comment by bluepnume** [comment]
That's strange.

Can you share your xcomponent code? Are you specifying `dimensions?`

**Comment by NitinWabale** [comment]
we are specifying dimensions.

**Comment by bluepnume** [comment]
Weird. Running out of ideas here -- again would be great to see the `xcomponent.create` code to try and narrow this down.

Are you by any chance running safari in full-screen mode?

**Comment by bluepnume** [comment]
Any updates on this? Are people still seeing this, and if so do you have safari in full screen mode?
