### ISSUE TITLE
Error: Unable to delegate rendering. Possibly the component is not loaded in the target window.

### ISSUE THREAD

**Issue by jmc265** [krakenjs/xcomponent#66]
I am getting the error "unable to delegate rendering" when attempting to use ```renderPopupTo(window.parent, {})```.

**Comment by jmc265** [comment]
I found that my component needs to include ```remoteRenderDomain: '*',``` in the spec.

So my component now looks like:

```
window.Button = xcomponent.create({
    tag: 'button',
    url: 'http://localhost:8008/build/button.html',
    remoteRenderDomain: '*',
    dimensions: {
        width: 200,
        height: 100
    },
    props: {
        ...
    }
});
```

**Comment by bluepnume** [comment]
That's correct. Added https://github.com/krakenjs/xcomponent/issues/68 -- maybe we can be smart and remove the need for `remoteRenderDomain`.

By the way -- ideally `remoteRenderDomain` should not be a FQDN rather than `*`, otherwise you're explicitly saying "any child component can try to render this component to my page" including components you don't necessarily own. Shouldn't be a problem if you're not rendering any third-party components, but doesn't hurt to be sure.

**Comment by bluepnume** [comment]
https://github.com/krakenjs/xcomponent/issues/68 is fixed and published. `xcomponent` will now just enforce the same-domain rule.
