### ISSUE TITLE
Recieving No ack for postMessage xcomponent_init in 1000ms with iframe component rendering in IE10

### ISSUE THREAD

**Issue by mmairs9** [krakenjs/xcomponent#96]

**Comment by bluepnume** [comment]
What domain are you testing on?

Do you see the same issue when you try on http://krakenjs.com/xcomponent/demo/basic/iframe/index.htm ?

**Comment by mmairs9** [comment]
Im testing on  an internal intranet sharepoint domain.  The iframe loads for a sec then it disappears. It happens sporadically so its like the page takes 2 long to load and then it destroys itself. Can i stop this from  happening?

**Comment by mmairs9** [comment]
Is there a prop so the component wont destroy itself or i can i set a timeout on this to give the page more time to render?

**Comment by mmairs9** [comment]
Im also loading 3 components in the one script but only 2 of them are ever used on same page.

**Comment by bluepnume** [comment]
I think it'll be the intranet that's the problem. I've seen the same problem with paypal components on IE10/11 in intranet mode.

Should be able to confirm that with http://krakenjs.com/xcomponent/demo/basic/iframe/index.htm -- since that domain isn't on your intranet, it should hopefully work without any problems.

The fix may be to:
- See if you can disable intranet mode in IE for your domain, or
- Add something to your hosts file so you can test against your intranet servers with a different domain name

**Comment by mmairs9** [comment]
the xcomponent code seems to be destroying the component and iframe however. It does render for a split second then destroys itself probably ebacuse it doesnt set up the postmessage bridge in time. Can we stop this from happeing?

**Comment by bluepnume** [comment]
Yeah, the default behavior of xcomponent is to destroy the component in the case of any errors -- since failing early is better than failing on some more ambiguous problem later, if part of the rendering process didn't work correctly.

In your case you want to keep the component open, even though it may not be able to communicate with the parent later when it needs to (like, for instance, when it tries to call a prop)?

**Comment by bluepnume** [comment]
BTW -- here's the intranet check I have for the paypal xcomponents: https://github.com/paypal/paypal-checkout/blob/master/src/lib/device.js#L94-L117

^ This may be useful if you want to prevent rendering at all in intranet mode.

**Comment by mmairs9** [comment]
Can we override that behavior to destroy or add a large timeout?

**Comment by bluepnume** [comment]
How would the large timeout help, if intranet mode prevents communications entirely?

**Comment by mmairs9** [comment]
its loads mosts times so it does render the xcomponent, the odd time it doesnt load and destroys itself.

**Comment by mmairs9** [comment]
sorry it does load for a second then destroys itself so i can see the component there.

**Comment by bluepnume** [comment]
Hmm ok. Might need to do some more investigation into this then. So you're saying most times it loads for longer than a second, and stays on the page?

**Comment by mmairs9** [comment]
yea majority of the time it loads fine. We are able to recreate this issue consistently though
Recieving No ack for postMessage xcomponent_init in 1000ms

**Comment by bluepnume** [comment]
On non-intranet domains also?

**Comment by mmairs9** [comment]
all domains are on the internal network but only one is sharepoint based. It does work on sharepoint most times like i said but we are seeing it disappear when the page takes longer to load.

**Comment by mmairs9** [comment]
Also seeing this in the console. Accessing the 'caller' property of a function or arguments object is not allowed in strict mode

**Comment by bluepnume** [comment]
Do you see any of the aforementioned problems when loading http://krakenjs.com/xcomponent/demo/basic/iframe/index.htm ? Trying to narrow down how much of this is related to intranet mode.

**Comment by mmairs9** [comment]
no i'm not able to recreate this on your demo site. As a temp fix is there anyway to increase the timeout on that postMessage ACK?

**Comment by mmairs9** [comment]
Im pretty sure because i have more than one iframe on the page that the message is being consumed by another post Message handler and not making it back in time for the postMessageACK. Chrome doesnt seem to destroy the component but in ie it appears too.

**Comment by mmairs9** [comment]
To help recreate when opening dev tools and setting a breakpoint before the postmessage is recieved i can see this error each time. Would it be difficult to add an option to not fail fast cause i imagine in some use cases you would want this or to make that timeout configurable. Thanks for looking into this!

**Comment by mmairs9** [comment]
Hi @bluepnume have you had any time to look into this. Is this a configurable option by postrobot/xcomponent or shall I submit a PR? I have had to revert the xcomponent code out of our project due to this bug we see happening but i much prefer your implementation.

**Comment by bluepnume** [comment]
I've added an export for `postRobot` to xcomponent so you can do:

`xcomponent.postRobot.CONFIG.ACK_TIMEOUT = 5000`

Again -- not sure that this will solve the problem, since it's only happening for you in intranet mode. I'd really like to know if it works to add an entry to your etc/hosts file, to trick IE into thinking it's a non-intranet site.

**Comment by mmairs9** [comment]
Unfortunately I wont be able to modify the hosts file for our organization.

 I did try that export as seen it before in an earlier post. I receive  -

 Uncaught TypeError: Cannot read property 'CONFIG' of undefined

I don't see that postRobot object available on the xcomponent object that
is created.

**Comment by bluepnume** [comment]
Hi, I just published a new version with that export.

Can you not change the hosts file on your local machine?

**Comment by mmairs9** [comment]
I can but it still seems to be forcing quirks mode. The timeout i believe
should do the trick for us. Thanks again!
